### PR TITLE
Add package.json to install `instant-markdown-d` when add VIM plugin.

### PR DESCRIPTION
**Pull request by buildpeak**
An easier way to install all dependencies in one-shot.

### CODE REVIEW

**Comment by ashwinvis** [comment]
Cool idea. Do you notice any lag from Vim trying to "resolve" the executable?

**Comment by buildpeak** [comment]
No, on my laptop.

**Comment by ashwinvis** [comment]
Thanks for the contrib. I finally tried this PR. Could you:

- [ ] remove the yarn.lock
- [ ] update `doc/vim-instant-markdown.txt` with some explanation of the new command
- [ ] make use of Vim's builtin function `executable('instant-markdown-d')` as the first check, before trying to resolve the executable under the plugin directory?

I get `:InstantMarkdownDPath` as `-1` because I have it installed globally.

**Comment by ashwinvis** [comment]
Followed up in #193

**Pull request closed without merging**
